{{- if not .Values.secret.secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docker-auth.name" . }}
type: Opaque
data:
  server.pem: {{ .Values.secret.data.server.certificate | b64enc | quote }}
  server.key: {{ .Values.secret.data.server.key | b64enc | quote }}
{{- end }}
